"""autogenerated by genpy from ceres_amu/AMU.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class AMU(genpy.Message):
  _md5sum = "dbdcdf66fe0e5834bd3a982cef95bb82"
  _type = "ceres_amu/AMU"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float32 xaccel # G 
float32 yaccel
float32 zaccel

float32 droll  # deg/sec
float32 dpitch
float32 dyaw

float32 roll   # deg
float32 pitch
float32 yaw

float32 status

"""
  __slots__ = ['xaccel','yaccel','zaccel','droll','dpitch','dyaw','roll','pitch','yaw','status']
  _slot_types = ['float32','float32','float32','float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       xaccel,yaccel,zaccel,droll,dpitch,dyaw,roll,pitch,yaw,status

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(AMU, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.xaccel is None:
        self.xaccel = 0.
      if self.yaccel is None:
        self.yaccel = 0.
      if self.zaccel is None:
        self.zaccel = 0.
      if self.droll is None:
        self.droll = 0.
      if self.dpitch is None:
        self.dpitch = 0.
      if self.dyaw is None:
        self.dyaw = 0.
      if self.roll is None:
        self.roll = 0.
      if self.pitch is None:
        self.pitch = 0.
      if self.yaw is None:
        self.yaw = 0.
      if self.status is None:
        self.status = 0.
    else:
      self.xaccel = 0.
      self.yaccel = 0.
      self.zaccel = 0.
      self.droll = 0.
      self.dpitch = 0.
      self.dyaw = 0.
      self.roll = 0.
      self.pitch = 0.
      self.yaw = 0.
      self.status = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_10f.pack(_x.xaccel, _x.yaccel, _x.zaccel, _x.droll, _x.dpitch, _x.dyaw, _x.roll, _x.pitch, _x.yaw, _x.status))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 40
      (_x.xaccel, _x.yaccel, _x.zaccel, _x.droll, _x.dpitch, _x.dyaw, _x.roll, _x.pitch, _x.yaw, _x.status,) = _struct_10f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_10f.pack(_x.xaccel, _x.yaccel, _x.zaccel, _x.droll, _x.dpitch, _x.dyaw, _x.roll, _x.pitch, _x.yaw, _x.status))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 40
      (_x.xaccel, _x.yaccel, _x.zaccel, _x.droll, _x.dpitch, _x.dyaw, _x.roll, _x.pitch, _x.yaw, _x.status,) = _struct_10f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_10f = struct.Struct("<10f")
